### ISSUE TITLE
Switch to MIT/BSD/Apache license?

### ISSUE THREAD

**Issue by gabel** [mcustiel/phiremock#15]
Could it be an option to switch phiremock and phiremock-codeception to a not so strict license regarding code publish when distributing the software, e.g. MIT, BSD or Apache?

**Comment by mcustiel** [comment]
Hi @gabel 
Thank you for your suggestion. My position right now is that phiremock is a tool to be used during development/acceptance and there is no strong need to redistribute it. 
If there's the case it needs to be modified and/or redistributed, then I go with GNU since it is not restrictive but empowering freedom.
Again, thank you very much.
Best regards,
Mariano.
