### ISSUE TITLE
minimum-stability suggestion

### ISSUE THREAD

**Issue by luceos** [mcustiel/phiremock#8]
Hi, first off great library!

I'd like to point out that setting minimum-stability to dev without adding prefer-stable true is very risky. All dependencies of the composer.json will then be loaded under dev stability, instead of possible stable.

**Comment by mcustiel** [comment]
Hello, Daniël. Thank you very much for the suggestion. I did it like that because I have a dependency in master branch of react/http so I needed dev as minimum, but now they removed what I needed so I have to refactor the code and probably will depend in a released version. But I need some time first :) I will keep this open as a reminder to push me and make some time for it.

**Comment by mcustiel** [comment]
Moin, I will close this since it was fixed by @mrIncompetent.
